version: '3.4'

services:
  goldenroutereact:
    image: goldenroutereact
    build:
      context: golden-route-react
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
      - 4100:4100
      - 4200:4200
  goldenroutebackend:
      image: goldenroutebackend
      build:
        context: ts-node-express
        dockerfile: ./Dockerfile
      environment:
        NODE_ENV: production
      ports:
        - 4100:4100
        - 4200:4200